# Generated by Django 5.0.6 on 2024-05-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('country_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=15)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
