# Generated by Django 5.0.6 on 2024-05-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_pages', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
